### ISSUE TITLE
Lack of updates

### ISSUE THREAD

**Issue by zayd62** [zayd62/mkdocs-versioning#40]
Hi all

This project is getting a lot of attention and currently, no one is able to build there docs using this plugin and there are several issues.

- [x] outdated dependecies (as seen in dependabot)
- [x] permission errors #32 
- [x] terrible documentation (partial fix in #39) 

Unfortunately, these issues came at the worst possible time. Im a final year computer science student and all my modules seem to have deadlines for coursework right after each other. Combine that with a final year project, a module which is 100% coursework and applying for jobs, This project has to take the back seat

thankfully, @timvink proposed a fix to #37 in #38. 

So this is me forcing myself to manage my time better and hopefully, once I have sorted out most of my deadlines and made progress in my project and coursework, I will go through and try and fix as many errors as possible and start closing some issues.

this was just an idea I had over the summer of 2019 and I let life get out of control so thanks for your patience and hopefully, a new  **working ** version of the plugin should be released.

**Comment by timvink** [comment]
Hi @zayd62, 

Thanks for explaining, and of course we understand. You don't have to explain, and there should be no guilt what so ever. I like how homebrew [puts it](https://github.com/Homebrew/brew/blob/bbed7246bc5c5b7acb8c1d427d10b43e090dfd39/docs/Maintainers-Avoiding-Burnout.md#2-no-guilt-about-leaving):

> All maintainers can stop working on Homebrew at any time without any guilt or explanation (like a job). We may still ask for your help with questions after you leave but you are under no obligation to answer them.

That said, it's a nice plugin and I see a use-case for my team. Perhaps we can help maintain it as a community. I maintain [several MkDocs plugins](https://github.com/timvink) and would be willing to help out and at least bring the plugin back to working order. Would you consider [inviting me as a collaborator to your repository](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository) and adding `timvink` as a collaborator to https://pypi.org/project/mkdocs-versioning/ ?
