### ISSUE TITLE
Add an option to allow hiding the version navigation bar

### ISSUE THREAD

**Issue by feranwq** [zayd62/mkdocs-versioning#57]
We only want to show a fixed version of a document to our customers, not all of them.

**Comment by zayd62** [comment]
the whole point of the plugin is that it keeps track of **all** the versions that have been **already built** in the `site` directory. if the folder does not "exist" in the site directory, then it will not appear in the version selection page. perhaps you can compress the versions you are not interested in, build the documentation and then uncompress, that way the version does not appear in the version selection page.

perhaps you can take adavantage of git branching and letting mkdocs build into a completely different directory, not the default `site` directory/

Maybe if you can justify further as to why this would be a needed feature i could consider it further but, in my opinion, having this option goes against the whole point of the plugin. i belive that all versions of documentation should be available. one of the few reasons why you would want to remove different versions is **security**

Also next time, please use the issue templates as opposed to creating a blank issue

**Comment by feranwq** [comment]
Thanks for the reply, we want to show different versions to different customers, but all versions are still maintained centrally by us, this should not be a normal feature, I will close this issue.
